### ISSUE TITLE
Pipeline status link in README is broken

### ISSUE THREAD

**Issue by jreznot** [EPadronU/balin#10]
It seems that this badge does not work anymore

```
[![pipeline status](https://gitlab.com/EPadronU/balin/badges/master/pipeline.svg)](https://gitlab.com/EPadronU/balin/commits/master)
```

**Comment by EPadronU** [comment]
Thank you for pointing that out. I removed it in commit 4f9b7f2. The Gitlab mirror of this repo doesn't exist anymore, thus the pipeline doesn't either.
