### ISSUE TITLE
release to jcenter?

### ISSUE THREAD

**Issue by rburgst** [EPadronU/balin#2]
I would like to use balin for testing, it doesnt look as if its already published to any artifact repository. Would this be possible?

**Comment by EPadronU** [comment]
Hi there. You're right. I have not released it to any artifact repository yet. Right now it's very very raw. I'll keep the possibility in mind.

**Comment by EPadronU** [comment]
Hi @rburgst. I just published an [artifact to bintray](https://bintray.com/epadronu/maven/balin).
